server:
  port: 80

spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:studytime;NON_KEYWORDS=USER

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    #open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
