PATCH http://localhost:80/study/1/approve
Content-Type: application/json

{
  "userAccount" : "jiwon"
}

###스터디 참여
POST http://localhost/study/1
Content-Type: application/json

{
  "userAccount" : "jiwon"
}


###스터디조회
GET http://localhost/study/1

###스터디 등록 거절
PATCH http://localhost/study/refuse/1779

###스터디 등록 승인
PATCH http://localhost/study/approve/1



###스터디 목록
GET http://localhost/study
Accept: application/json
Content-Type: application/json

{

}

###스터디 등록
POST http://localhost/study
Content-Type: application/json

{
  "title" : "제목입니다.",
  "content" : "내용입니다.",
  "userAccount" : "jiwona",
  "city" : "서울시",
  "period" : "one",
  "expiredAt" : "2023-06-25",
  "category" : "coding",
  "recruitCnt" : 3,
  "processType" : "ON",
  "startedAt" : "2023-06-27"
}





